version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306  
      # - MYSQL_ROOT_HOST="%"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/booking?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306  
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - CUSTOM_RABBITMQ_QUEUE_NAME=booking
    networks:
      - springboot-mysql-network
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - 8090:8090


  email:
    build:
      context: .
      dockerfile: ./email/Dockerfile
    container_name: email
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - CUSTOM_RABBITMQ_QUEUE_NAME=booking
      - SIMPLEJAVAMAIL_SMTP_HOST=smtp.default.com
      - SIMPLEJAVAMAIL_SMTP_PORT=25
      - CUSTOM_SIMPLEJAVAMAIL_HOST=smtp.yopmail.com
      - CUSTOM_SIMPLEJAVAMAIL_PORT=25
    depends_on:
      - rabbitmq
    # ports:
    #   - 8082:8080


volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network