= Traccia 2: Prenotazione biglietti
:mermaid-format: svg

La prova consiste nel creare un'applicazione web che espone delle API (quindi solo back-end).

Crea un servizio di prenotazione posti per eventi.
I vincoli sono:

* Non si possono prenotare più di 3 biglietti per evento a transazione
* Si possono prenotare più eventi a transazione
* Ogni evento ha un numero limitato di posti
* (Opzionale) Dovrebbe essere possibile ricevere una notifica (email, sms, ecc.) dell'avvenuta transazione (anche simulata)

Non ci interessa il CRUD degli utenti e degli eventi che puoi inserire manualmente a database o nella fonte dati che sceglierai.


== System Context Diagram

image::./resources/images/system.svg[System,width=640,height=480,opts=inline]

== Container Diagram

image::./resources/images/container.svg[Container,width=960,height=720,opts=inline]

== Component Diagram

image::./resources/images/component.svg[Component,width=1280,height=960,opts=inline]

== Data Model

[mermaid, target=model]
....
classDiagram
    

    class Reservation{
      String id
      List~Ticket~ tickets
    }
    class Event {
      String id
      int maxTickets
      int remainingTickets
    }
    class Ticket {
      String id
      Event event
      Attendee attendee
    }

    class Attendee {
       String id
       String firstName
       String lastName
       int birthDate
    }
   
   Attendee "1" -- "1..*" Ticket
   Event "1" -- "1..*" Ticket
   Reservation "1" -- "1..3" Ticket
....