server:
  port : 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  # rabbitmq:
  #   host: localhost
  #   port: 5672
  #   username: guest
  #   password: guest

custom: #used for custom properties
  rabbitmq:
    queue:
      name: booking

# logging:
#   level:
#     root: DEBUG
