/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import static org.example.app.MessageUtils.getMessage;


public class App {
    public static void main(String[] args) {
        System.out.println(getMessage());
    }
}
