/*
 * This source file was generated by the Gradle 'init' task
 */
package it.berkhel.app;

import static it.berkhel.app.MessageUtils.getMessage;


public class App {
    public static void main(String[] args) {
        System.out.println(getMessage());
    }
}
